package com.example.dart.model;

import com.example.dart.model.enums.ShotType;

import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class ValidShots {
    public static Set<Shot> VALID_SHOTS = Stream.of(
            new Shot(1, ShotType.SINGLE),
            new Shot(2, ShotType.SINGLE),
            new Shot(3, ShotType.SINGLE),
            new Shot(4, ShotType.SINGLE),
            new Shot(5, ShotType.SINGLE),
            new Shot(6, ShotType.SINGLE),
            new Shot(7, ShotType.SINGLE),
            new Shot(8, ShotType.SINGLE),
            new Shot(9, ShotType.SINGLE),
            new Shot(10, ShotType.SINGLE),
            new Shot(11, ShotType.SINGLE),
            new Shot(12, ShotType.SINGLE),
            new Shot(13, ShotType.SINGLE),
            new Shot(14, ShotType.SINGLE),
            new Shot(15, ShotType.SINGLE),
            new Shot(16, ShotType.SINGLE),
            new Shot(17, ShotType.SINGLE),
            new Shot(18, ShotType.SINGLE),
            new Shot(19, ShotType.SINGLE),
            new Shot(20, ShotType.SINGLE),
            new Shot(25, ShotType.SINGLE),
            new Shot(1, ShotType.DOUBLE),
            new Shot(2, ShotType.DOUBLE),
            new Shot(3, ShotType.DOUBLE),
            new Shot(4, ShotType.DOUBLE),
            new Shot(5, ShotType.DOUBLE),
            new Shot(6, ShotType.DOUBLE),
            new Shot(7, ShotType.DOUBLE),
            new Shot(8, ShotType.DOUBLE),
            new Shot(9, ShotType.DOUBLE),
            new Shot(10, ShotType.DOUBLE),
            new Shot(11, ShotType.DOUBLE),
            new Shot(12, ShotType.DOUBLE),
            new Shot(13, ShotType.DOUBLE),
            new Shot(14, ShotType.DOUBLE),
            new Shot(15, ShotType.DOUBLE),
            new Shot(16, ShotType.DOUBLE),
            new Shot(17, ShotType.DOUBLE),
            new Shot(18, ShotType.DOUBLE),
            new Shot(19, ShotType.DOUBLE),
            new Shot(20, ShotType.DOUBLE),
            new Shot(25, ShotType.DOUBLE),
            new Shot(1, ShotType.TRIPLE),
            new Shot(2, ShotType.TRIPLE),
            new Shot(3, ShotType.TRIPLE),
            new Shot(4, ShotType.TRIPLE),
            new Shot(5, ShotType.TRIPLE),
            new Shot(6, ShotType.TRIPLE),
            new Shot(7, ShotType.TRIPLE),
            new Shot(8, ShotType.TRIPLE),
            new Shot(9, ShotType.TRIPLE),
            new Shot(10, ShotType.TRIPLE),
            new Shot(11, ShotType.TRIPLE),
            new Shot(12, ShotType.TRIPLE),
            new Shot(13, ShotType.TRIPLE),
            new Shot(14, ShotType.TRIPLE),
            new Shot(15, ShotType.TRIPLE),
            new Shot(16, ShotType.TRIPLE),
            new Shot(17, ShotType.TRIPLE),
            new Shot(18, ShotType.TRIPLE),
            new Shot(19, ShotType.TRIPLE),
            new Shot(20, ShotType.TRIPLE)
    ).collect(Collectors.toUnmodifiableSet());
}
