package com.example.dart.model.enums;

public enum PlayerStatisticsOrderType {
    BY_GAMES_PLAYED,
    BY_SHOTS_FIRED,
    BY_GAMES_WON_PERCENTAGE,
    BY_TRIPLE_20_HITS_PERCENTAGE,
    BY_DOUBLE_20_HITS_PERCENTAGE,
    BY_SINGLE_20_HITS_PERCENTAGE,
    BY_DOUBLE_25_HITS_PERCENTAGE,
    BY_SINGLE_25_HITS_PERCENTAGE,
    BY_TRIPLE_HITS_PERCENTAGE,
    BY_DOUBLE_HITS_PERCENTAGE
}
